### ISSUE TITLE
The compilation gets broken

### ISSUE THREAD

**Issue by Dengjianping** [arkworks-rs/r1cs-tutorial#4]
The whole project cannot be compiled, due to `ark-crypto-primitives` is always going to pull the latest commit from github.
But it compiled while I used specified [commit](https://github.com/arkworks-rs/crypto-primitives/commit/1223fe4e2cdb2a11d3336c08151812eb958988ec)

Platform:
rust: 1.52.1
os: ubuntu 20.04

Perhaps that `Cargo.lock` file can avoid this situation.

**Comment by weikengchen** [comment]
Thanks! I changed the dependency to the latest versions.
